name: Unix Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Format files
        run: find include src test -type f -not -name "doctest.h" -a \( -name "*.cc" -o -name "*.h" \) -print0 | xargs -0 clang-format -i

      - name: Check for differences
        run: |
          git status --porcelain
          git status --porcelain | xargs -I {} -0 test -z \"{}\"

  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: macOS Release
            cxx: clang++
            cc: clang
            toolset: clang
            toolset-version: 12
            cxxflags: "-stdlib=libc++"
            mode: Release
            os: macos-latest
            artifact: pkg-macos-amd64
            postfix: osx
          - name: GCC 9 Release
            cxx: g++-9
            cc: gcc-9
            toolset: gcc
            toolset-version: 9
            cxxflags: ""
            mode: Release
            os: ubuntu-latest
    env:
      BUILDCACHE_COMPRESS: true
      BUILDCACHE_ACCURACY: SLOPPY
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools
      BUILDCACHE_DIR: ${{ github.workspace }}/.buildcache
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # ==== BUILD ====
      - name: CMake
        run: |
          cmake \
            -S . -B build \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_CXX_FLAGS="${{ matrix.config.cxxflags }}" \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.mode }}

      - name: Build
        run: cmake --build build --target pkg pkg-test

      - name: Run Tests
        run: ./build/pkg-test

      # ==== DISTRIBUTION ====
      - name: Strip Executable
        run: strip build/pkg

      - name: Upload Distribution (1)
        uses: actions/upload-artifact@v2
        if: matrix.config.artifact != ''
        with:
          name: ${{ matrix.config.artifact }}
          path: ./build/pkg

      - name: Upload Distribution (2)
        uses: actions/upload-artifact@v2
        if: matrix.config.postfix != ''
        with:
          name: pkg${{ matrix.config.postfix }}
          path: ./build/pkg

      # ==== RELEASE ====
      - name: Upload Release (1)
        if: github.event.action == 'published' && matrix.config.artifact != ''
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/pkg
          asset_name: ${{ matrix.config.artifact }}
          asset_content_type: application/x-tar

      - name: Upload Release (2)
        if: github.event.action == 'published' && matrix.config.postfix != ''
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/pkg
          asset_name: pkg${{ matrix.config.postfix }}
          asset_content_type: application/x-tar

  static-build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.14
    steps:
      - name: Install packages
        run: apk add git build-base cmake ninja linux-headers

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: CMake
        run: |
          cmake \
            -S . -B build \
            -G Ninja \
            -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++ -static" \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --target pkg pkg-test

      - name: Run Tests
        run: ./build/pkg-test

      # ==== DISTRIBUTION ====
      - name: Strip Executable
        run: strip build/pkg

      - name: Upload Distribution (1)
        uses: actions/upload-artifact@v2
        with:
          name: pkg-linux-amd64
          path: ./build/pkg

      - name: Upload Distribution (2)
        uses: actions/upload-artifact@v2
        with:
          name: pkg
          path: ./build/pkg

      # ==== RELEASE ====
      - name: Upload Release (1)
        if: github.event.action == 'published'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/pkg
          asset_name: pkg-linux-amd64
          asset_content_type: application/x-tar

      - name: Upload Release (2)
        if: github.event.action == 'published'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/pkg
          asset_name: pkg
          asset_content_type: application/x-tar
